---

- name: Set Login Banner for All Network Devices
connection: network_cli
gather_facts: false
hosts: all
become: yes
become_method: enable
tasks:

  - name: configure the login banner
    ios_banner:
      banner: login
      text: |
        Welcome to the OSPFPacket Lab!
        Happy Learning!
      state: present
