---

- name: Set Login Banner and Loopback0 description for All Network Devices
  connection: network_cli
  gather_facts: false
  hosts: routers
  tasks:

    - name: configure the login banner
      ios_banner:
        banner: login
        text: |
          Welcome to the OSPFPacket Lab!
          Happy Learning!!
        state: present

    - name: config loopback interface description
      ios_interface:
        name: Loopback0
        description: 'Loopback0 Interface Created by Anisble'

- name: Configure ISAKMP and IPSEC attributes for Tunnel0
  connection: network_cli
  gather_facts: false
  hosts: tunnelrouters
  tasks:

    - name: config isakmp policy
      ios_config:
        lines:
          - encr aes
          - authentication pre-share
          - group 5
          - hash md5
        parents: crypto isakmp policy 10

    - name: config isakmp key & ipsec transform-set
      ios_config:
        lines:
          - crypto isakmp key cisco address 0.0.0.0
          - crypto ipsec transform-set ESP_AES_SHA esp-aes esp-sha-hmac

    - name: config ipsec profile
      ios_config:
        lines:
          - set transform-set ESP_AES_SHA
        parents: crypto ipsec profile DMVPN_PROFILE
